import { test, expect } from '@playwright/test'

test('real API polygons, tooltips, selection, time changes and mobile layout', async ({ page, request }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  const polygons = page.locator('.leaflet-overlay-pane path')
  await expect(polygons).toHaveCount(263)
  await expect(page.getByRole('heading', { name: 'Ride-Hailing Demand Predictor' })).toBeVisible()
  await expect(page.locator('.legend')).toContainText('150+')
  const before = await page.locator('.recommendation').allTextContents()
  const expected = await (await request.get('http://127.0.0.1:8000/api/recommend?day=Mon&hour=18&top=5')).json()
  await expect(page.locator('.recommendation').first()).toContainText(expected.recommendations[0].zoneName)
  await page.locator('.recommendation').first().click()
  await expect(page.locator('.selection-card')).toContainText(expected.recommendations[0].zoneName)
  await expect(page.locator('.leaflet-overlay-pane path[stroke="#f1ac35"]')).toHaveCount(1)
  await page.locator('.leaflet-overlay-pane path[stroke="#f1ac35"]').dispatchEvent('mouseover')
  await expect(page.locator('.leaflet-tooltip')).toContainText('Monday · 18:00')
  await expect(page.locator('.leaflet-tooltip')).toContainText('Predicted pickups:')
  await page.locator('.leaflet-overlay-pane path').first().dispatchEvent('click')
  await expect(page.locator('.selection-card')).toContainText('SELECTED ZONE · 1')
  await page.getByRole('combobox').selectOption('Sat')
  await expect(page.locator('.time-badge')).toHaveText('Saturday · 18:00')
  await expect(polygons).toHaveCount(263)
  expect(await page.locator('.recommendation').allTextContents()).not.toEqual(before)
  const saturday = await page.locator('.recommendation').allTextContents()
  await page.getByRole('slider').fill('9')
  await expect(page.locator('.time-badge')).toHaveText('Saturday · 09:00')
  expect(await page.locator('.recommendation').allTextContents()).not.toEqual(saturday)
  await page.getByRole('button', { name: 'Clear selected zone' }).click()
  await page.waitForTimeout(1000)
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(polygons).toHaveCount(263)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true })
  expect(errors).toEqual([])
})

test('failure and retry recover without backend changes', async ({ page }) => {
  await page.route('**/api/demand?**', route => route.abort())
  await page.goto('/')
  await expect(page.getByRole('alert')).toContainText('Unable to connect')
  await page.unroute('**/api/demand?**')
  await page.getByRole('button', { name: 'Retry' }).click()
  await expect(page.locator('.leaflet-overlay-pane path')).toHaveCount(263)
})

test('empty state and latest selection wins after delayed response', async ({ page }) => {
  await page.route('**/api/demand?**', async route => {
    if (route.request().url().includes('hour=18')) {
      const response = await route.fetch()
      await new Promise(resolve => setTimeout(resolve, 1200))
      await route.fulfill({ response }).catch(() => {})
    } else await route.continue()
  })
  const initialRequest = page.waitForRequest(request => request.url().includes('/api/demand?day=Mon&hour=18'))
  await page.goto('/')
  await initialRequest
  await page.getByRole('slider').fill('10')
  await expect(page.locator('.time-badge')).toHaveText('Monday · 10:00')
  await page.waitForTimeout(1500)
  await expect(page.locator('.time-badge')).toHaveText('Monday · 10:00')
  await page.unroute('**/api/demand?**')
  // Only exercise the empty/error UI; map integration above uses real predictions.
  await page.route('**/api/demand?**', route => route.fulfill({ json: { day: 'Tue', hour: 10, data: [] } }))
  await page.getByRole('combobox').selectOption('Tue')
  await expect(page.locator('.state-card')).toHaveText('No demand data available.')
})
